### ISSUE TITLE
Instructions for running functions with Bazel

### ISSUE THREAD

**Issue by barapa** [GoogleCloudPlatform/functions-framework-java#100]

**Comment by josephlewis42** [comment]
Thanks for the suggestion. Bazel is probably outside the scope of this project.

If you're looking for the full reproducibility and high fidelity that Bazel builds provide, it's likely you'd want to build a full docker container with it rather than trying to merge Bazel with a lot of the magic that https://github.com/GoogleCloudPlatform/buildpacks provides when containerizing functions-framework-java code.

If you have a more concrete use-case, please feel free to re-open the issue with details about what you're trying to achieve. 

Thanks!
