### ISSUE TITLE
How to test BackgroundFunction<PubSubMessage>

### ISSUE THREAD

**Issue by tclass** [GoogleCloudPlatform/functions-framework-java#103]
How would I run the BackgroundFunction locally? Do I also use the functionTarget and Port? Does it not need to connect to GCP and read from a pubsub topic?

```
./gradlew runFunction -Prun.functionTarget=com.example.HelloWorld \
                      -Prun.port=8080
```

**Comment by anniefu** [comment]
There are some instructions for this in the Node repo here: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/events.md

While it is the node repo, the testing instructions are generally the same for Pub/Sub except:
1. You should start up your Java function instead of a Node function
2. If you use the Pub/Sub emulator, the script is written in node, but there are alternative instructions for that step here: https://cloud.google.com/pubsub/docs/emulator
